import test from 'node:test';import assert from 'node:assert/strict';import {PDFDocument,PDFName,PDFString} from 'pdf-lib';import jpeg from 'jpeg-js';import {PNG} from 'pngjs';import {unzipSync} from 'fflate';import bcrypt from 'bcryptjs';import {env,reset,objects,faults} from './runtime';import {validateInput,displayName,LIMITS} from '../lib/shared';import {mergeFiles,signature,orient} from '../lib/pipeline';import {POST as upload} from '../app/api/submissions/route';import {POST as login} from '../app/api/admin/login/route';import {POST as logout} from '../app/api/admin/logout/route';import {GET as list} from '../app/api/admin/submissions/route';import {GET as download,DELETE as remove} from '../app/api/admin/file/[id]/route';import {GET as bulk} from '../app/api/admin/bulk/route';
const origin='https://school.test';let ip=0;function req(path:string,method='GET',body?:any,cookie='',extra:Record<string,string>={}){return new Request(origin+path,{method,body,headers:{origin,cookie,'cf-connecting-ip':String(++ip),...extra}})}
async function pdf(width=200,count=1){const d=await PDFDocument.create();for(let i=0;i<count;i++)d.addPage([width,300]);return new File([await d.save() as any],'bai.pdf',{type:'application/pdf'})}
function img(kind='jpg',w=30,h=50,alpha=255){const data=Buffer.alloc(w*h*4);for(let i=0;i<data.length;i+=4){data[i]=200;data[i+1]=50;data[i+2]=100;data[i+3]=alpha}const bytes=kind==='png'?PNG.sync.write({data,width:w,height:h}):jpeg.encode({data,width:w,height:h},90).data;return new File([bytes],`bai.${kind}`,{type:kind==='png'?'image/png':'image/jpeg'})}
async function send(files:File[],g='GRADE_8',d='TUESDAY',id=crypto.randomUUID()){const f=new FormData();f.set('studentName','Nguyễn Minh Anh');f.set('grade',g);f.set('studyDay',d);f.set('requestId',id);files.forEach(x=>f.append('files',x));return upload(req('/api/submissions','POST',f))}
async function admin(){env.ADMIN_PASSWORD_HASH=await bcrypt.hash('test-password-only',4);const r=await login(req('/api/admin/login','POST',JSON.stringify({password:'test-password-only'})));assert.equal(r.status,200);const cookie=r.headers.get('set-cookie')!;for(const flag of ['HttpOnly','Secure','SameSite=Strict','Max-Age=28800'])assert.ok(cookie.includes(flag));return cookie.split(';')[0]}
test('input validation, Unicode NFC, enums and safe filenames',()=>{assert.equal(displayName(validateInput('  Nguyễn   Minh Anh  ','GRADE_8','MONDAY')),'Nguyễn Minh Anh - Lớp 8 - Tối Thứ 2.pdf');assert.equal(validateInput('Nguyễn Minh Anh','GRADE_8','MONDAY').studentName,'Nguyễn Minh Anh');for(const n of ['','  ','a'.repeat(101),'../secret','<script>','An\r\nX-Header: yes'])assert.throws(()=>validateInput(n,'GRADE_8','MONDAY'));for(const g of ['8','GRADE_11','__proto__'])assert.throws(()=>validateInput('Minh Anh',g,'MONDAY'));for(const d of ['SUNDAY','toString'])assert.throws(()=>validateInput('Minh Anh','GRADE_8',d))});
test('PDF single/multiple/multipage and page order',async()=>{for(const [fs,n] of [[[await pdf()],1],[[await pdf(201),await pdf(202)],2],[[await pdf(203,4)],4]] as [File[],number][]){const r=await mergeFiles(fs);assert.equal((await PDFDocument.load(r.bytes)).getPageCount(),n)}const r=await mergeFiles([await pdf(201),await pdf(202,2)]);assert.deepEqual((await PDFDocument.load(r.bytes)).getPages().map(x=>x.getWidth()),[201,202,202])});
for(const [label,kind,w,h,a] of [['portrait','jpg',30,50,255],['landscape','jpg',60,30,255],['transparency','png',30,50,80],['long image','png',10,2000,255],['higher resolution','jpg',1200,1600,255]] as const)test('image '+label,async()=>{const r=await mergeFiles([img(kind,w,h,a)]),p=(await PDFDocument.load(r.bytes)).getPage(0);assert.equal(r.pageCount,1);assert.equal(p.getWidth(),w>h?842:595)});
test('JPEG extension and actual EXIF orientation',async()=>{const src=Buffer.from(await img('jpg',60,30).arrayBuffer());const exif=Buffer.from('45786966000049492a0008000000010012010300010000000600000000000000','hex'),head=Buffer.alloc(4);head[0]=255;head[1]=225;head.writeUInt16BE(exif.length+2,2);const file=new File([src.subarray(0,2),head,exif,src.subarray(2)],'rotated.jpeg',{type:'image/jpeg'});const r=await mergeFiles([file]);assert.equal((await PDFDocument.load(r.bytes)).getPage(0).getWidth(),595)});
test('multiple images and mixed PDF/image order',async()=>{for(const fs of [[img(),img()],[img(),await pdf(222)],[await pdf(222),img()],[img(),await pdf(222),img('png'),await pdf(333)]]){const r=await mergeFiles(fs),pages=(await PDFDocument.load(r.bytes)).getPages();assert.equal(pages.length,fs.length);if(fs.length===4)assert.deepEqual(pages.map(x=>x.getWidth()),[595,222,595,333])}});
test('EXIF mappings 1–8 preserve all pixels',()=>{const data=new Uint8Array([1,0,0,255,2,0,0,255,3,0,0,255,4,0,0,255,5,0,0,255,6,0,0,255]);assert.deepEqual(Array.from(orient(data,2,3,6).data).filter((_,i)=>i%4===0),[5,3,1,6,4,2]);for(let i=1;i<=8;i++){const r=orient(data,2,3,i);assert.equal(r.width*r.height,6);assert.deepEqual(Array.from(r.data).filter((_,j)=>j%4===0).sort(),[1,2,3,4,5,6])}});
test('reject false extension/MIME, corrupt PDF/image, active PDF',async()=>{assert.throws(()=>signature(new Uint8Array([1,2,3])));await assert.rejects(mergeFiles([new File(['%PDF-1.7 corrupted'],'fake.pdf',{type:'application/pdf'})]));const f=await pdf();await assert.rejects(mergeFiles([new File([f],'fake.jpg',{type:'image/jpeg'})]));await assert.rejects(mergeFiles([new File([f],'fake.pdf',{type:'image/png'})]));const p=await PDFDocument.create();p.addPage();p.catalog.set(PDFName.of('OpenAction'),p.context.obj({S:'JavaScript',JS:PDFString.of('alert(1)')}));await assert.rejects(mergeFiles([new File([await p.save() as any],'active.pdf',{type:'application/pdf'})]));await assert.rejects(mergeFiles([new File([new Uint8Array([255,216,255,0,0])],'bad.jpg',{type:'image/jpeg'})]))});
test('reject annotations rather than silently lose handwriting',async()=>{const p=await PDFDocument.create(),page=p.addPage();page.node.set(PDFName.of('Annots'),p.context.obj([{Type:'Annot',Subtype:'Ink'}]));await assert.rejects(mergeFiles([new File([await p.save() as any],'ink.pdf',{type:'application/pdf'})]),/chú thích/)});
test('size/count/pages/pixels limits including total upload',async()=>{await assert.rejects(mergeFiles([]));await assert.rejects(mergeFiles(Array(21).fill(await pdf())));await assert.rejects(mergeFiles([new File([new Uint8Array(LIMITS.file+1)],'large.pdf')]));await assert.rejects(mergeFiles(Array(3).fill(new File([new Uint8Array(LIMITS.file)],'large.pdf'))));await assert.rejects(mergeFiles([await pdf(200,101)]));const b=Buffer.from(await img('png').arrayBuffer());b.writeUInt32BE(99999,16);await assert.rejects(mergeFiles([new File([b],'bomb.png',{type:'image/png'})]))});
test('authentication, cookies, authorization, CSRF, logout and brute force',async()=>{reset();for(const f of [()=>list(req('/api/admin/submissions')),()=>bulk(req('/api/admin/bulk?grade=GRADE_8&day=TUESDAY')),()=>download(req('/api/admin/file/x'),{params:Promise.resolve({id:'x'})}),()=>remove(req('/api/admin/file/x','DELETE'),{params:Promise.resolve({id:'x'})})])assert.equal((await f()).status,401);const c=await admin();assert.equal((await list(req('/api/admin/submissions','GET',undefined,c))).status,200);assert.equal((await login(req('/api/admin/login','POST',JSON.stringify({password:'wrong'})))).status,401);assert.equal((await logout(req('/api/admin/logout','POST',undefined,c,{origin:'https://evil.test'}))).status,403);await logout(req('/api/admin/logout','POST',undefined,c));assert.equal((await list(req('/api/admin/submissions','GET',undefined,c))).status,401);for(let i=0;i<6;i++)assert.equal((await login(req('/api/admin/login','POST',JSON.stringify({password:'wrong'}),'',{'cf-connecting-ip':'brute'}))).status,i<5?401:429)});
test('upload/store/download/Unicode/idempotency/duplicates/soft delete',async()=>{reset();const c=await admin(),f=await pdf(),id=crypto.randomUUID(),r=await send([f],'GRADE_8','TUESDAY',id);assert.equal(r.status,201);const row:any=await r.json();assert.equal(row.studentName,'Nguyễn Minh Anh');assert.equal((await (await send([f],'GRADE_8','TUESDAY',id)).json() as any).id,row.id);assert.notEqual((await (await send([f])).json() as any).id,row.id);assert.equal(objects.size,2);const d=await download(req('/api/admin/file/'+row.id,'GET',undefined,c),{params:Promise.resolve({id:row.id})});assert.equal(d.status,200);assert.match(decodeURIComponent(d.headers.get('content-disposition')!),/Nguyễn Minh Anh - Lớp 8 - Tối Thứ 3.pdf/);assert.equal((await PDFDocument.load(await d.arrayBuffer())).getPageCount(),1);assert.equal((await remove(req('/api/admin/file/'+row.id,'DELETE',undefined,c),{params:Promise.resolve({id:row.id})})).status,200);assert.equal((await download(req('/api/admin/file/'+row.id,'GET',undefined,c),{params:Promise.resolve({id:row.id})})).status,404);assert.equal(objects.size,2);assert.equal((await (await list(req('/api/admin/submissions','GET',undefined,c))).json() as any).total,1)});
test('storage/DB errors never report success and retries recover',async()=>{for(const which of ['put','db'] as const){reset();faults[which]=true;const id=crypto.randomUUID(),f=await pdf();assert.equal((await send([f],'GRADE_8','MONDAY',id)).status,503);faults[which]=false;assert.equal((await send([f],'GRADE_8','MONDAY',id)).status,201);assert.equal(objects.size,1)}});
test('bulk: 25/20/30 group isolation, Unicode collisions, selection, deletion, readable PDFs',async()=>{reset();const c=await admin(),file=await pdf(),ids:string[]=[];for(const [g,d,n] of [['GRADE_8','TUESDAY',25],['GRADE_8','FRIDAY',20],['GRADE_9','TUESDAY',30]] as const)for(let i=0;i<n;i++){const r=await send([file],g,d);assert.equal(r.status,201);const v:any=await r.json();if(g==='GRADE_8'&&d==='TUESDAY')ids.push(v.id)}const r=await bulk(req('/api/admin/bulk?grade=GRADE_8&day=TUESDAY','GET',undefined,c));assert.equal(r.status,200);const zip=unzipSync(new Uint8Array(await r.arrayBuffer()));assert.equal(Object.keys(zip).length,25);for(const [name,b] of Object.entries(zip)){assert.match(name,/Nguyễn Minh Anh - Lớp 8 - Tối Thứ 3/);assert.equal((await PDFDocument.load(b)).getPageCount(),1)}const selected=await bulk(req('/api/admin/bulk?grade=GRADE_8&day=TUESDAY&ids='+ids.slice(0,2).join(','),'GET',undefined,c));assert.equal(Object.keys(unzipSync(new Uint8Array(await selected.arrayBuffer()))).length,2);await remove(req('/api/admin/file/'+ids[0],'DELETE',undefined,c),{params:Promise.resolve({id:ids[0]})});const filtered=await bulk(req('/api/admin/bulk?grade=GRADE_8&day=TUESDAY','GET',undefined,c));assert.equal(Object.keys(unzipSync(new Uint8Array(await filtered.arrayBuffer()))).length,24);assert.equal((await bulk(req('/api/admin/bulk?grade=GRADE_8','GET',undefined,c))).status,400)});

test('large valid PDF within 5 MB remains readable',async()=>{const f=await pdf(),original=Buffer.from(await f.arrayBuffer()),padding=Buffer.from('\n%'+'.'.repeat(4*1024*1024)+'\n'),large=new File([original,padding],'large.pdf',{type:'application/pdf'});const r=await mergeFiles([large]);assert.equal((await PDFDocument.load(r.bytes)).getPageCount(),1)});
test('SQL injection filter and arbitrary IDs cannot escape group',async()=>{reset();const c=await admin();await send([await pdf()]);const response=await list(req('/api/admin/submissions?q='+encodeURIComponent("' OR 1=1 --"),'GET',undefined,c));assert.equal(response.status,200);assert.equal((await response.json() as any).total,0);const bad=await bulk(req('/api/admin/bulk?grade=GRADE_8&day=TUESDAY&ids='+encodeURIComponent("' OR 1=1 --"),'GET',undefined,c));assert.equal(bad.status,400)});

test('grade 10 submission, filter isolation, download and ZIP naming',async()=>{reset();const c=await admin(),f=await pdf();await send([f],'GRADE_8');const r=await send([f],'GRADE_10');assert.equal(r.status,201);const row:any=await r.json();assert.equal(row.grade,'GRADE_10');const result:any=await (await list(req('/api/admin/submissions?grade=GRADE_10','GET',undefined,c))).json();assert.equal(result.total,1);assert.equal(result.rows[0].grade,'GRADE_10');const file=await download(req('/api/admin/file/'+row.id,'GET',undefined,c),{params:Promise.resolve({id:row.id})});assert.match(decodeURIComponent(file.headers.get('content-disposition')!),/Lớp 10/);const zip=await bulk(req('/api/admin/bulk?grade=GRADE_10&day=TUESDAY','GET',undefined,c));assert.equal(zip.status,200);assert.match(zip.headers.get('content-disposition')!,/Lop-10-Toi-Thu-3/);assert.equal(Object.keys(unzipSync(new Uint8Array(await zip.arrayBuffer()))).length,1)});

import {GET as homeworkGet,POST as homeworkSave,DELETE as homeworkDelete} from '../app/api/homework/[grade]/route';
import {GET as homeworkFile} from '../app/api/homework/[grade]/file/route';
const hwctx=(grade='GRADE_8')=>({params:Promise.resolve({grade})});
async function saveHomework(c:string,file:File,grade='GRADE_8',expectedId=''){const f=new FormData();f.set('file',file);f.set('expectedId',expectedId);return homeworkSave(req('/api/homework/'+grade,'POST',f,c),hwctx(grade))}
test('homework: authenticated publishing, class isolation, inline files, replacement and deletion',async()=>{reset();const c=await admin();assert.equal((await saveHomework('',await pdf())).status,401);assert.equal((await (await homeworkGet(req('/api/homework/GRADE_8'),hwctx())).json() as any).homework,null);for(const [grade,file,type] of [['GRADE_8',await pdf(),'application/pdf'],['GRADE_9',img('png'),'image/png'],['GRADE_10',img(),'image/jpeg']] as const){const saved=await saveHomework(c,file,grade);assert.equal(saved.status,201,await saved.clone().text());const h:any=(await saved.json() as any).homework;assert.equal(h.grade,grade);assert.equal(h.storageKey,undefined);const view=await homeworkFile(req(h.url),hwctx(grade));assert.equal(view.status,200);assert.equal(view.headers.get('content-type'),type);assert.match(view.headers.get('content-disposition')!,/^inline/);assert.ok((await view.arrayBuffer()).byteLength>0)}const old:any=(await (await homeworkGet(req('/api/homework/GRADE_8'),hwctx())).json() as any).homework;assert.equal((await saveHomework(c,await pdf(),'GRADE_8','stale')).status,409);const changed=await saveHomework(c,img('png'),'GRADE_8',old.id);assert.equal(changed.status,201);const next:any=(await changed.json() as any).homework;assert.notEqual(old.id,next.id);assert.equal((await homeworkFile(req(old.url),hwctx())).status,404);assert.equal(objects.size,3);assert.equal((await homeworkDelete(req('/api/homework/GRADE_8?id='+old.id,'DELETE',undefined,c),hwctx())).status,409);assert.equal((await homeworkDelete(req('/api/homework/GRADE_8?id='+next.id,'DELETE',undefined,c),hwctx())).status,200);assert.equal((await homeworkFile(req(next.url),hwctx())).status,404);assert.equal(objects.size,2);assert.equal((await homeworkGet(req('/api/homework/GRADE_11'),hwctx('GRADE_11'))).status,400)});
test('homework: rejected files, CSRF and failed storage preserve current assignment',async()=>{reset();const c=await admin();const first:any=(await (await saveHomework(c,await pdf())).json() as any).homework;assert.equal((await saveHomework(c,new File(['bad'],'fake.png',{type:'image/png'}),'GRADE_8',first.id)).status,400);faults.put=true;assert.equal((await saveHomework(c,await pdf(),'GRADE_8',first.id)).status,503);faults.put=false;faults.homeworkDb=true;assert.equal((await saveHomework(c,await pdf(),'GRADE_8',first.id)).status,503);faults.homeworkDb=false;const after:any=(await (await homeworkGet(req('/api/homework/GRADE_8'),hwctx())).json() as any).homework;assert.equal(after.id,first.id);assert.equal(objects.size,1);const form=new FormData();form.set('file',await pdf());form.set('expectedId',first.id);assert.equal((await homeworkSave(req('/api/homework/GRADE_8','POST',form,c,{origin:'https://other.test'}),hwctx())).status,403);assert.equal((await homeworkDelete(req('/api/homework/GRADE_8?id='+first.id,'DELETE'),hwctx())).status,401)});
