'use client';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,UploadCloud,Trash2} from 'lucide-react';
import {grades,formatTime} from '@/lib/shared';
import type {Homework} from '@/lib/homework';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
type Assignment=Homework&{url:string};
export function HomeworkPanel({grade,manage=false}:{grade:string;manage?:boolean}){
 const [opened,setOpened]=useState(manage),[data,setData]=useState<Assignment|null>(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[file,setFile]=useState<File|null>(null),[reload,setReload]=useState(0);const input=useRef<HTMLInputElement>(null);
 useEffect(()=>{if(!opened||!grade)return;const controller=new AbortController();setLoading(true);setError('');fetch('/api/homework/'+grade,{signal:controller.signal,cache:'no-store'}).then(async r=>{const d=await r.json() as {homework:Assignment|null;error?:string};if(!r.ok)throw Error(d.error||'Không tải được bài tập.');setData(d.homework);setLoaded(true)}).catch(e=>{if(!controller.signal.aborted)setError(e.message)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[grade,opened,reload]);
 async function mutate(remove=false){if(busy)return;setBusy(true);setError('');setNotice('');try{const form=new FormData();if(!remove){if(!file)throw Error('Hãy chọn tệp bài tập.');form.set('file',file);form.set('expectedId',data?.id||'')}const r=await fetch('/api/homework/'+grade+(remove?'?id='+data?.id:''),{method:remove?'DELETE':'POST',body:remove?undefined:form});const d=await r.json() as {homework:Assignment|null;error?:string};if(r.status===401){location.assign('/admin/login');return}if(!r.ok)throw Error(d.error||'Không thể cập nhật bài tập.');setData(remove?null:d.homework);setFile(null);if(input.current)input.current.value='';setNotice(remove?'Đã xóa bài tập hiện tại.':'Đã lưu bài tập. Học sinh có thể xem ngay.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <div className="homework-panel">
 {!manage&&<button type="button" className="outline-button" disabled={!grade} onClick={()=>{setOpened(true);setReload(n=>n+1)}}><BookOpen size={18}/>Xem bài tập về nhà</button>}
 {!manage&&!grade&&<p className="tiny muted">Em hãy chọn lớp trước khi xem bài tập.</p>}
 {opened&&grade&&<div className="homework-content"><h3>Bài tập Vật lý · {grades[grade as keyof typeof grades]}</h3>
 {loading&&<p role="status">Đang tải bài tập…</p>}{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status" className="status-line">{notice}</p>}
 {loaded&&!loading&&!data&&<p>Hiện tại chưa có bài tập về nhà cho lớp này.</p>}
 {loaded&&!loading&&data&&<><p className="homework-filename">{data.filename}</p><p className="tiny muted">Cập nhật: {formatTime(data.updatedAt)}</p>{data.contentType==='application/pdf'?<><iframe key={data.id} className="homework-pdf" title={'Bài tập Vật lý '+grades[grade as keyof typeof grades]} src={data.url}/><p className="tiny muted">Nếu trình duyệt không hiển thị PDF, hãy mở tệp bằng liên kết bên dưới.</p></>:<img className="homework-image" src={data.url} alt={'Bài tập Vật lý '+grades[grade as keyof typeof grades]} onError={()=>setError('Chưa hiển thị được ảnh. Hãy tải lại bài tập.')}/>}<a className="outline-button" href={data.url} target="_blank" rel="noopener noreferrer">Mở tệp bài tập</a></>}
 {manage&&<div className="homework-editor"><label className="field-label" htmlFor={'homework-file-'+grade}>Tệp bài tập mới</label><input ref={input} id={'homework-file-'+grade} type="file" accept=".pdf,.png,.jpg,.jpeg" disabled={busy||loading} onChange={e=>{setFile(e.target.files?.[0]||null);setNotice('')}}/><p className="tiny muted">Một tệp PDF, JPG hoặc PNG · Tối đa 5 MB · PDF tối đa 100 trang · Ảnh tối đa 8 MP. Lưu tệp mới sẽ thay bài đang giao cho lớp này.</p><div className="homework-actions"><button type="button" className="primary-button" disabled={busy||loading||!loaded||!file} onClick={()=>mutate()}><UploadCloud size={17}/>{busy?'Đang xử lý…':'Lưu bài tập'}</button><button type="button" className="outline-button" disabled={busy||loading} onClick={()=>setReload(n=>n+1)}>Tải lại</button>{data&&<AlertDialog><AlertDialogTrigger asChild><button type="button" className="outline-button" disabled={busy||loading}><Trash2 size={17}/>Xóa bài tập</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Xóa bài tập của {grades[grade as keyof typeof grades]}?</AlertDialogTitle><AlertDialogDescription>Học sinh sẽ không còn thấy bài tập này. Bạn có thể giao tệp mới sau đó.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Giữ lại</AlertDialogCancel><AlertDialogAction onClick={()=>mutate(true)}>Xóa bài tập</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}</div></div>}
 </div>}</div>
}
export function HomeworkManager(){const [grade,setGrade]=useState('GRADE_8');return <section className="panel homework-manager"><h2>Quản lý bài tập tuần này</h2><p className="muted">Chọn lớp để xem, thay đổi hoặc xóa bài tập Vật lý đang giao.</p><RadioGroup aria-label="Lớp giao bài tập" className="choice-grid homework-grades" value={grade} onValueChange={setGrade}>{Object.entries(grades).map(([key,label])=><label className={'choice '+(grade===key?'active':'')} key={key}><RadioGroupItem value={key}/>{label}</label>)}</RadioGroup><HomeworkPanel key={grade} grade={grade} manage/></section>}
