import {env} from 'cloudflare:workers';import bcrypt from 'bcryptjs';
export function db(){if(!env.DB)throw Error('DATABASE_UNAVAILABLE');return env.DB}export function bucket(){if(!env.BUCKET)throw Error('STORAGE_UNAVAILABLE');return env.BUCKET}
export const json=(v:unknown,status=200,headers:Record<string,string>={})=>Response.json(v,{status,headers:{'Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
export class HttpError extends Error{constructor(public status:number,message:string){super(message)}}
export function error(e:unknown){if(e instanceof HttpError)return json({error:e.message},e.status);console.error('Request failed',e instanceof Error?e.name:'Unknown');return json({error:'Không thể hoàn tất. Hãy giữ tệp và thử lại sau.'},503)}
export function sameOrigin(r:Request){if(r.headers.get('origin')!==new URL(r.url).origin)throw new HttpError(403,'Yêu cầu không hợp lệ. Hãy tải lại trang.')}
export async function sha(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(n=>n.toString(16).padStart(2,'0')).join('')}
export async function rate(r:Request,kind:string,max:number,seconds:number){const now=Math.floor(Date.now()/1000),key=kind+':'+await sha(r.headers.get('cf-connecting-ip')||'unknown')+':'+Math.floor(now/seconds);const row=await db().prepare('INSERT INTO rates (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+seconds).first<{count:number}>();if(!row||row.count>max)throw new HttpError(429,'Thao tác quá nhiều lần. Vui lòng chờ một lát rồi thử lại.');await db().prepare('DELETE FROM rates WHERE expires_at < ?').bind(now-3600).run()}
export async function bounded(r:Request,max:number){if(Number(r.headers.get('content-length'))>max)throw new HttpError(413,'Dung lượng yêu cầu quá lớn.');if(!r.body)throw new HttpError(400,'Yêu cầu không có dữ liệu.');const chunks:Uint8Array[]=[];let count=0;const reader=r.body.getReader();while(true){const {done,value}=await reader.read();if(done)break;count+=value.byteLength;if(count>max){await reader.cancel();throw new HttpError(413,'Dung lượng yêu cầu quá lớn.')}chunks.push(value)}const data=new Uint8Array(count);let off=0;for(const c of chunks){data.set(c,off);off+=c.length}return data}
export function cookieToken(r:Request){return r.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith('__Host-admin='))?.slice(13)||''}
export async function requireAdmin(r:Request){const token=cookieToken(r);if(!/^[a-f0-9]{64}$/.test(token))throw new HttpError(401,'Vui lòng đăng nhập quản trị.');if(!await db().prepare('SELECT expires_at FROM sessions WHERE token_hash=? AND expires_at>?').bind(await sha(token),Date.now()).first())throw new HttpError(401,'Phiên đăng nhập đã hết hạn.');return token}
export async function verifyPassword(password:string){const hash=(env as unknown as Record<string,string>).ADMIN_PASSWORD_HASH;if(!hash)throw new HttpError(503,'Chưa cấu hình mật khẩu quản trị.');if(!password||new TextEncoder().encode(password).length>72)return false;return bcrypt.compare(password,hash)}
export function sessionCookie(token:string,maxAge=28800){return `__Host-admin=${token}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${maxAge}`}
export function disposition(filename:string,inline=false){return `${inline?'inline':'attachment'}; filename="${filename.endsWith('.zip')?'submissions.zip':'submission.pdf'}"; filename*=UTF-8''${encodeURIComponent(filename).replace(/['()*]/g,c=>'%'+c.charCodeAt(0).toString(16))}`}
